name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          body: |
            Protocol Buffers definitions for the User service.

            ## Install in a Go service

            ```bash
            go get github.com/nalrematvonesah/user.proto@${{ github.ref_name }}
            ```

            ```go
            import userv1 "github.com/nalrematvonesah/user.proto/gen/user/v1"
            ```
